version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - api.x.xlife.top
          - auth.x.xlife.top
          - ws.ranger.x.xlife.top
          - pma.x.xlife.top
          - e.x.xlife.top
          - monitor.x.xlife.top
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.x.xlife.top'
      traefik.port: 8080
