- key:               ethereum-devnet
  name:              Ethereum
  client:            ethereum
  server:            http://geth:8545
  height:            1
  min_confirmations: 1
  explorer:
    address:         https://rinkeby.etherscan.io/address/#{address}
    transaction:     https://rinkeby.etherscan.io/tx/#{txid}
  status:            active
