- id:                    usd
  symbol:                '$'
  type:                  fiat
  precision:             2
  base_factor:           1
  enabled:               true
  min_deposit_amount:    0
  min_collection_amount: 0
  withdraw_limit_24h:    100
  withdraw_limit_72h:    200
  deposit_fee:           0
  withdraw_fee:          0

- id:                    eth
  blockchain_key:        ethereum-devnet
  symbol:                'Ξ'
  type:                  coin
  precision:             8
  base_factor:           1_000_000_000_000_000_000
  enabled:               true
  min_deposit_amount:    0.00021
  min_collection_amount: 0.00021
  withdraw_limit_24h:    0.2
  withdraw_limit_72h:    0.5
  deposit_fee:           0
  withdraw_fee:          0
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ETH
    json_rpc_endpoint:        http://bc.xlife.top:8544
    wallet_url_template:      http://bc.xlife.top/addr/#{address}
    transaction_url_template: http://bc.xlife.top/tx/#{txid}

- id:                     btc
  blockchain_key:         btc-testnet
  symbol:                 '฿'
  type:                   coin
  precision:              8
  base_factor:            100_000_000
  enabled:                true
  min_deposit_amount:     0.0000356
  min_collection_amount:  0.0000356
  withdraw_limit_24h:     0.1
  withdraw_limit_72h:     0.2
  deposit_fee:            0
  withdraw_fee:           0
  options:
    case_sensitive:                   true
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             true
    allow_multiple_deposit_addresses: false
    api_client: BTC
    json_rpc_endpoint:        http://admin:changeme@bitcoind:18332
    wallet_url_template:      https://testnet.blockchain.info/address/#{address}
    transaction_url_template: https://testnet.blockchain.info/tx/#{txid}
